name: Functional Tests
run-name: DISPATCH.FunctionalTests (${{ github.event.workflow_run.head_branch }})

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  FunctionalTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Get Branch Settings
        id: settings
        run: |
          $json = Get-Content .github/branch.json | ConvertFrom-Json
          $installation = $json.installation
          echo "ue=$installation" >> $env:GITHUB_OUTPUT
        shell: powershell
      - name: Clean Workspace
        uses: ./.github/actions/workspace-clean
      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          ue-installation: ${{ steps.settings.outputs.ue }}
      - name: Add Status Check
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              name: 'tests-functional',
              head_sha: '${{ github.event.workflow_run.head_sha }}',
              status: 'in_progress',
              conclusion: 'neutral',
              output: {
                title: 'Functional Tests',
                summary: 'In Progress'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            })
      - name: Run Functional Tests
        uses: ./.github/actions/ue-cmd-tests
        with:
          ue-installation: ${{ steps.settings.outputs.ue }}
          tests: 'Functional Tests'
      - name: Parse UE Log
        id: parse-log
        if: always()
        uses: ./.github/actions/ue-parse-log
      - name: Update Status Check
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              name: 'tests-functional',
              head_sha: '${{ github.event.workflow_run.head_sha }}',
              status: 'completed',
              conclusion: '${{ steps.parse-log.outcome }}',
              output: {
                title: 'Functional Tests',
                summary: '${{ steps.parse-log.outcome }}'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            })          
      - name: Parse Test Results
        if: always()
        uses: ./.github/actions/ue-parse-results
      - name: Gather And Upload Artifacts
        if: always()
        uses: ./.github/actions/upload-artifacts
        with:
          artifact-name: 'schedule-functional-tests-${{ github.run_number }}'      
      - name: Update Summary
        if: always()
        shell: powershell
        run: |
          $markdownPath = "${{ github.workspace }}\Staging\TestResults\index.md"
          if(Test-Path -Path $markdownPath)
          {
            $markdownLines = Get-Content -Path $markdownPath
            $outputPath = $env:GITHUB_STEP_SUMMARY
            Write-Output "Updating GITHUB_STEP_SUMMARY with $outputPath."
            foreach ($line in $markdownLines) 
            {
              Write-Output "$line" >> $outputPath
            }
          }